/**
 * @file test_scope_property.cpp
 * @brief Stateful property test for `memsafe::Scope` create/destroy sequences.
 *
 * @details
 * Work package: CPP_MEMSAFE-0330-TEST.
 *
 * Purpose:
 * - Exercise the finalized CPP_MEMSAFE-0300-FUNC `memsafe::Scope` artifact
 *   through generated stateful command sequences.
 * - Use the CPP_MEMSAFE-0035-TEST `property_driver.hpp` threshold and seed
 *   machinery so the property lane runs at least 1 000 sequences in normal CI
 *   and receives the documented nightly multiplier automatically.
 * - Report the failing deterministic seed and the smallest replay prefix known
 *   to reproduce an invariant failure.
 *
 * Key invariants:
 * - Every tracked object constructor increments the per-scope construction
 *   count exactly once.
 * - Destroying a live `memsafe::Scope` invokes exactly one destructor for every
 *   successfully created object owned by that scope.
 * - Destructors run in strict reverse creation order, matching the Slice 3
 *   RAII arena requirement for last-in, first-out teardown.
 * - `Scope::size()` tracks the number of created objects while a generated
 *   scope episode is still alive, and no object is destroyed before that
 *   episode's scope is destroyed.
 *
 * Ownership and thread-safety:
 * - All generated state is owned by one test process and one test thread.
 * - Scope-owned raw pointers are used only while their owning scope is alive;
 *   post-scope raw-pointer access remains the sanitizer-only oracle covered by
 *   CPP_MEMSAFE-0320-TEST.
 */
#include "../../test_harness.hpp"

#include "../support/property_driver.hpp"

#include <memsafe/scope.hpp>

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <limits>
#include <memory>
#include <random>

namespace {

/// Maximum generated command count for one stateful Scope property sequence.
constexpr std::size_t k_max_commands_per_sequence = 64u;

/// Percentage chance that a live generated scope is destroyed at a command step.
constexpr std::size_t k_destroy_command_percent = 30u;

/// Exclusive upper bound for tracked payload values generated by the property.
constexpr std::size_t k_payload_value_count = 1000u;

/// Sentinel prefix limit that means "execute the full generated sequence".
constexpr std::size_t k_full_sequence_prefix =
    (std::numeric_limits<std::size_t>::max)();

/**
 * @brief Return a deterministic bounded value from a Mersenne Twister engine.
 *
 * @param rng Random engine owned by the active property sequence.
 * @param exclusive_upper Exclusive upper bound for the returned value.
 * @return A value in the half-open range `[0, exclusive_upper)`.
 * @pre `exclusive_upper > 0`.
 * @post `rng` has advanced by one draw and no global state is modified.
 * @invariant The function uses direct modulo reduction so replay is based only
 * on the standardized `std::mt19937_64` output stream, not on implementation
 * details of `std::uniform_int_distribution`.
 * @throws Nothing.
 * @note Ownership/thread-safety: borrows the caller-owned engine for the
 * duration of the call. The small modulo bias is acceptable here because this
 * property needs broad randomized command coverage rather than statistical
 * sampling guarantees.
 */
std::size_t bounded_random(std::mt19937_64& rng,
                           std::size_t exclusive_upper) noexcept {
    const std::uint64_t raw = rng();
    const std::uint64_t bound = static_cast<std::uint64_t>(exclusive_upper);
    return static_cast<std::size_t>(raw % bound);
}

/**
 * @brief Mutable lifetime ledger for one generated `memsafe::Scope` episode.
 *
 * @details
 * Each episode ledger outlives the `memsafe::Scope` that owns the tracked
 * objects for that episode. This lets the property check destructor counts and
 * destruction order after the generated scope has been destroyed.
 *
 * @pre A ledger must remain alive until every `tracked_scope_object` that
 * references it has been destroyed.
 * @post Direct field updates represent observed construction and destruction
 * events for exactly one generated scope episode.
 * @invariant `destruction_order[index]` stores the creation id destroyed at
 * that zero-based destruction index when `index < destroyed`.
 * @throws Nothing; the aggregate owns only fixed-size storage.
 * @note Ownership/thread-safety: owned by the property sequence stack frame and
 * accessed by one test thread.
 */
struct episode_log final {
    /// Number of tracked constructors completed in this scope episode.
    std::size_t constructed = 0u;
    /// Number of tracked destructors observed in this scope episode.
    std::size_t destroyed = 0u;
    /// Creation ids in the order their destructors were observed.
    std::array<std::size_t, k_max_commands_per_sequence> destruction_order{};
    /// True if the destruction-order array would have overflowed.
    bool overflowed = false;

    /**
     * @brief Allocate the next creation id and record a construction event.
     *
     * @return Creation id assigned to the object being constructed.
     * @pre The episode has not created more than
     * `k_max_commands_per_sequence` objects.
     * @post `constructed` has increased by one.
     * @invariant Creation ids are contiguous and increase from zero within one
     * generated scope episode.
     * @throws Nothing.
     * @note Ownership/thread-safety: called only by the single tracked-object
     * constructor currently running inside the property sequence.
     */
    std::size_t record_construction() noexcept {
        const std::size_t id = constructed;
        ++constructed;
        return id;
    }

    /**
     * @brief Record that a tracked object destructor ran.
     *
     * @param creation_id Creation id stored in the object being destroyed.
     * @return No value.
     * @pre The caller supplies the id that was returned by
     * `record_construction` for the same object.
     * @post `destroyed` has increased by one and the observed id is recorded
     * when fixed storage is available.
     * @invariant The ledger never allocates while a destructor is running,
     * preserving the `noexcept` destructor requirement imposed by
     * `memsafe::Scope::create<T>`.
     * @throws Nothing.
     * @note Ownership/thread-safety: called by `memsafe::Scope` during
     * generated single-threaded scope teardown.
     */
    void record_destruction(std::size_t creation_id) noexcept {
        if (destroyed < destruction_order.size()) {
            destruction_order[destroyed] = creation_id;
        } else {
            overflowed = true;
        }
        ++destroyed;
    }
};

/**
 * @brief Object type created inside generated `memsafe::Scope` episodes.
 *
 * @details
 * The object records construction and destruction in an external episode
 * ledger. Its destructor is deliberately allocation-free and `noexcept`, which
 * satisfies the `Scope::create<T>` compile-time contract while still exposing
 * enough state for the property to validate Scope teardown behavior.
 *
 * Example:
 * @code
 * episode_log log;
 * memsafe::Scope scope;
 * tracked_scope_object* object = scope.create<tracked_scope_object>(log, 7u);
 * CHECK(object->payload() == 7u);
 * @endcode
 *
 * @pre The supplied `episode_log` outlives this object.
 * @post Construction records one creation id; destruction records exactly one
 * destruction event for that id.
 * @invariant `log_` and `creation_id_` remain stable for the object's lifetime.
 * @throws Nothing; construction stores only pointers and integer values.
 * @note Ownership/thread-safety: instances are owned exclusively by
 * `memsafe::Scope` and are accessed on one test thread before scope teardown.
 */
class tracked_scope_object final {
public:
    /**
     * @brief Construct a tracked object and record its creation id.
     *
     * @param log Episode ledger that records this object's lifetime events.
     * @param payload_value Arbitrary payload used to prove the raw pointer is
     * usable while the owning scope is alive.
     * @return Constructors do not return a value.
     * @pre `log` remains alive until the owning `memsafe::Scope` destroys this
     * object.
     * @post `log.constructed` has increased by one and `creation_id()` returns
     * the id assigned by that increment.
     * @invariant The object stores a non-owning pointer to `log`; ownership of
     * the object itself belongs to `memsafe::Scope`.
     * @throws Nothing.
     * @note Ownership/thread-safety: constructed by `Scope::create` and used
     * only in the single-threaded property sequence that created it.
     */
    tracked_scope_object(episode_log& log,
                         std::size_t payload_value) noexcept
        : log_(&log),
          creation_id_(log.record_construction()),
          payload_(payload_value) {}

    /**
     * @brief Record this object's destruction in its episode ledger.
     *
     * @return Destructors do not return a value.
     * @pre `log_` points to the live ledger supplied at construction.
     * @post The ledger has one additional destruction event for
     * `creation_id_`.
     * @invariant The destructor performs no allocation and cannot throw.
     * @throws Nothing.
     * @note Ownership/thread-safety: invoked by the owning `memsafe::Scope`
     * during generated single-threaded teardown.
     */
    ~tracked_scope_object() noexcept {
        log_->record_destruction(creation_id_);
    }

    /**
     * @brief Return the creation id assigned within the current episode.
     *
     * @return Zero-based creation id.
     * @pre The object is alive.
     * @post The object is unchanged.
     * @invariant The returned id is stable for the object's lifetime.
     * @throws Nothing.
     * @note Ownership/thread-safety: observer only; the raw pointer used to
     * call this function is bounded by the owning `memsafe::Scope` lifetime.
     */
    [[nodiscard]] std::size_t creation_id() const noexcept {
        return creation_id_;
    }

    /**
     * @brief Return the generated payload value.
     *
     * @return Payload supplied at construction.
     * @pre The object is alive.
     * @post The object is unchanged.
     * @invariant The payload never changes after construction.
     * @throws Nothing.
     * @note Ownership/thread-safety: observer only and unsynchronized, used on
     * one test thread.
     */
    [[nodiscard]] std::size_t payload() const noexcept {
        return payload_;
    }

private:
    tracked_scope_object(const tracked_scope_object&) = delete;
    tracked_scope_object& operator=(const tracked_scope_object&) = delete;

    episode_log* log_;
    std::size_t creation_id_;
    std::size_t payload_;
};

/**
 * @brief Result of executing one generated Scope command sequence.
 *
 * @pre Default construction represents a passing sequence before any commands
 * have run.
 * @post Fields describe the first detected invariant failure, if any.
 * @invariant `ok == false` implies `reason` names the violated invariant and
 * `failing_step` identifies the one-based command prefix that exposed it.
 * @throws Nothing; the aggregate owns no dynamic storage.
 * @note Ownership/thread-safety: owned by one property sequence.
 */
struct sequence_report final {
    /// True when every checked Scope invariant held.
    bool ok = true;
    /// Number of commands generated before prefix truncation.
    std::size_t generated_steps = 0u;
    /// Number of generated commands actually executed for this replay.
    std::size_t executed_steps = 0u;
    /// One-based command index that first exposed a failure, or zero on pass.
    std::size_t failing_step = 0u;
    /// Static diagnostic string naming the violated invariant.
    const char* reason = "no failure";
};

/**
 * @brief Mark a sequence report as failed if it has not failed already.
 *
 * @param report Report to update.
 * @param step One-based command index associated with the failure.
 * @param reason Static diagnostic string naming the violated invariant.
 * @return No value.
 * @pre `reason != nullptr`.
 * @post The first failure is preserved and later failures do not overwrite it.
 * @invariant A sequence reports only the earliest observed invariant failure,
 * which keeps shrink diagnostics stable across replays.
 * @throws Nothing.
 * @note Ownership/thread-safety: mutates caller-owned local sequence state.
 */
void fail_sequence(sequence_report& report,
                   std::size_t step,
                   const char* reason) noexcept {
    if (report.ok) {
        report.ok = false;
        report.failing_step = step;
        report.reason = reason;
    }
}

/**
 * @brief Validate a destroyed Scope episode against destructor invariants.
 *
 * @param log Episode ledger whose owning `memsafe::Scope` has been destroyed.
 * @return True when destructor count and reverse destruction order are correct.
 * @pre The scope that owned the episode's tracked objects has already been
 * destroyed.
 * @post `log` is unchanged.
 * @invariant Passing episodes have `destroyed == constructed` and destruction
 * id sequence `constructed - 1, constructed - 2, ... , 0`.
 * @throws Nothing.
 * @note Ownership/thread-safety: reads fixed ledger storage owned by the
 * property sequence.
 */
bool destroyed_episode_is_valid(const episode_log& log) noexcept {
    if (log.overflowed) {
        return false;
    }
    if (log.destroyed != log.constructed) {
        return false;
    }

    for (std::size_t index = 0u; index < log.constructed; ++index) {
        const std::size_t expected = log.constructed - 1u - index;
        if (log.destruction_order[index] != expected) {
            return false;
        }
    }

    return true;
}

/**
 * @brief Execute one deterministic generated Scope command sequence.
 *
 * @param rng Random engine seeded by `property_driver.hpp` for this sequence.
 * @param prefix_limit Maximum number of generated commands to execute, or
 * `k_full_sequence_prefix` to execute the entire generated sequence.
 * @return Sequence report containing pass/fail status and replay metadata.
 * @pre `rng` must be the per-sequence engine supplied by
 * `memsafe::test_support::property::run_sequences`, or another engine seeded
 * with the reported failing sequence seed.
 * @post Any active generated scope has been destroyed before the function
 * returns, so all destructor-count and reverse-order checks have run.
 * @invariant The generated operation stream consists of create-object commands
 * and explicit destroy-scope commands; a final cleanup destroys any still-live
 * scope so every sequence observes a complete scope lifetime.
 * @throws `std::bad_alloc` if allocating the test-owned `memsafe::Scope` or
 * a scope-owned object fails. The property driver catches escaping exceptions
 * and converts them into failed results with seed metadata.
 * @note Ownership/thread-safety: all Scope instances and ledgers are local to
 * the sequence and single-threaded.
 */
sequence_report run_scope_sequence(std::mt19937_64& rng,
                                   std::size_t prefix_limit) {
    sequence_report report;
    report.generated_steps =
        1u + bounded_random(rng, k_max_commands_per_sequence);
    report.executed_steps = report.generated_steps < prefix_limit
                                ? report.generated_steps
                                : prefix_limit;

    std::array<episode_log, k_max_commands_per_sequence + 1u> episodes{};
    std::size_t episode_count = 0u;
    std::unique_ptr<memsafe::Scope> active_scope;
    episode_log* active_log = nullptr;

    const auto begin_scope = [&]() {
        if (episode_count >= episodes.size()) {
            fail_sequence(report, report.executed_steps,
                          "too many generated scope episodes");
            return;
        }

        episodes[episode_count] = episode_log{};
        active_log = &episodes[episode_count];
        ++episode_count;
        active_scope = std::make_unique<memsafe::Scope>();
    };

    const auto destroy_active_scope = [&](std::size_t step) {
        if (!active_scope) {
            return;
        }

        episode_log& finished = *active_log;
        active_scope.reset();

        if (!destroyed_episode_is_valid(finished)) {
            fail_sequence(report, step,
                          "destructor count or reverse order invariant failed");
        }

        active_log = nullptr;
    };

    const auto create_tracked_object = [&](std::size_t step) {
        if (!active_scope) {
            begin_scope();
        }
        if (!active_scope || active_log == nullptr) {
            fail_sequence(report, step, "failed to begin generated scope");
            return;
        }

        const std::size_t expected_id = active_log->constructed;
        const std::size_t payload = bounded_random(rng, k_payload_value_count);
        tracked_scope_object* const object =
            active_scope->create<tracked_scope_object>(*active_log, payload);

        if (object == nullptr) {
            fail_sequence(report, step, "Scope::create returned null");
        } else if (object->creation_id() != expected_id ||
                   object->payload() != payload) {
            fail_sequence(report, step,
                          "created object payload or id was corrupted");
        }

        if (active_scope->size() != active_log->constructed) {
            fail_sequence(report, step, "Scope::size did not track creates");
        }
        if (active_log->destroyed != 0u) {
            fail_sequence(report, step,
                          "Scope destroyed an object before scope teardown");
        }
    };

    for (std::size_t step = 1u; step <= report.executed_steps; ++step) {
        /*
         * F2 classifies Scope as a stateful property target. The generated
         * command stream therefore models state transitions: create within the
         * current scope, explicitly destroy the current scope, then begin a new
         * one on demand.
         */
        const bool can_destroy =
            active_scope != nullptr && active_log != nullptr &&
            active_log->constructed > 0u;
        const bool choose_destroy =
            can_destroy &&
            bounded_random(rng, 100u) < k_destroy_command_percent;

        if (choose_destroy) {
            destroy_active_scope(step);
        } else {
            create_tracked_object(step);
        }
    }

    /*
     * Every prefix replay must end at a complete Scope lifetime boundary so
     * shrinking can expose destructor-count/order failures even when the
     * original command stream did not randomly choose an explicit destroy.
     */
    destroy_active_scope(report.executed_steps);

    return report;
}

/**
 * @brief Replay one generated sequence from a deterministic sequence seed.
 *
 * @param seed Seed reported by `property_driver.hpp` for a specific sequence.
 * @param prefix_limit Command prefix to execute before forced final cleanup.
 * @return Sequence report for the replayed prefix.
 * @pre `seed` must be the per-sequence seed, not the property run base seed.
 * @post No global state is modified.
 * @invariant Replays use the same command generator as the property body.
 * @throws `std::bad_alloc` under the same conditions as `run_scope_sequence`.
 * @note Ownership/thread-safety: all replay state is local to the call.
 */
sequence_report replay_scope_sequence(std::uint64_t seed,
                                      std::size_t prefix_limit) {
    std::mt19937_64 rng(seed);
    return run_scope_sequence(rng, prefix_limit);
}

/**
 * @brief Find the smallest command prefix that still reproduces a failure.
 *
 * @param seed Per-sequence seed reported by the property driver.
 * @param original_steps Number of commands generated for the failing sequence.
 * @return Smallest prefix length in `[0, original_steps]` that fails, or
 * `original_steps` if no smaller failing prefix is found.
 * @pre The full generated sequence identified by `seed` has failed.
 * @post No global state is modified.
 * @invariant Prefixes are tested from shortest to longest to produce stable,
 * minimal diagnostics without requiring a full shrink tree.
 * @throws `std::bad_alloc` if a replay allocation fails.
 * @note Ownership/thread-safety: all replay attempts are independent and local.
 */
std::size_t find_minimal_failing_prefix(std::uint64_t seed,
                                        std::size_t original_steps) {
    for (std::size_t prefix = 0u; prefix <= original_steps; ++prefix) {
        if (!replay_scope_sequence(seed, prefix).ok) {
            return prefix;
        }
    }

    return original_steps;
}

/**
 * @brief Print property-driver failure metadata in the required replay format.
 *
 * @param result Failed property result returned by `run_sequences`.
 * @return No value.
 * @pre `result.passed() == false`.
 * @post A single diagnostic line containing seed and shrunk prefix metadata has
 * been written to standard error.
 * @invariant The emitted seed is the per-sequence replay seed stored in
 * `result.failure.seed`; the shrunk prefix is `result.failure.minimal_steps`.
 * @throws Nothing.
 * @note Ownership/thread-safety: writes to process-local `stderr`; no shared
 * library state is modified.
 */
void print_property_failure(
    const memsafe::test_support::property::run_result& result) noexcept {
    std::fprintf(stderr,
                 "property failure: name=%s seed=%llu sequence=%zu "
                 "original_steps=%zu shrunk_prefix=%zu detail=%s message=%s\n",
                 result.config.name.c_str(),
                 static_cast<unsigned long long>(result.failure.seed),
                 result.failure.failing_sequence,
                 result.failure.original_steps,
                 result.failure.minimal_steps,
                 result.failure.note.c_str(),
                 result.message.c_str());
}

} // namespace

/**
 * @brief Run the stateful `memsafe::Scope` property test.
 *
 * @retval 0 All generated sequences satisfied the Scope lifetime invariants.
 * @retval 1 One or more harness checks failed, with replay seed and shrunk
 * prefix reported for property failures.
 * @pre The executable is run by the F4 property lane, which discovers
 * `testing/tests/property/*.cpp` and defines any lane-specific property macros
 * before including `property_driver.hpp`.
 * @post The process exit code is the test verdict consumed by CTest.
 * @invariant At least the F2 stateful threshold is executed on a passing run,
 * and every generated Scope episode is destroyed before the test returns.
 * @throws The test does not intentionally throw. Unexpected allocation
 * failures inside the property body are caught by `property_driver.hpp` and
 * surfaced as property failures with seed metadata.
 * @note Ownership/thread-safety: all test state is automatic storage or
 * property-driver local state; no worker threads are started.
 */
int main() {
    namespace prop = memsafe::test_support::property;

    prop::run_config config =
        prop::make_config("scope.create-destroy.lifo",
                          prop::workload::stateful,
                          0x0330u);

    CHECK(config.sequence_count >= prop::stateful_base_threshold());
    CHECK(prop::sequence_threshold(prop::workload::stateful) >= 1000u);

    const prop::run_result result = prop::run_sequences(
        config,
        [](std::size_t sequence,
           std::mt19937_64& rng,
           prop::shrinking_metadata& shrink) {
            const sequence_report report =
                run_scope_sequence(rng, k_full_sequence_prefix);
            if (report.ok) {
                return true;
            }

            const std::size_t minimal_prefix =
                find_minimal_failing_prefix(shrink.seed,
                                            report.generated_steps);
            prop::record_shrink(shrink,
                                report.generated_steps,
                                minimal_prefix,
                                shrink.seed,
                                sequence,
                                report.reason);
            return false;
        });

    if (!result.passed()) {
        print_property_failure(result);
    }

    CHECK(result.passed());
    CHECK(result.executed_sequences >= prop::stateful_base_threshold());

    RUN_TESTS("test_scope_property");
}
